### ISSUE TITLE
重刷手机后一些组件报错

### ISSUE THREAD

**Issue by yccczzj** [evilbutcher/Scriptables#11]
b站 知乎 微博热点都报错了…
![E673FE96-C2EF-4C8A-A594-924E8BE3D95B](https://user-images.githubusercontent.com/67724199/104115272-8344b180-5348-11eb-808d-04e62640c884.png)
nasa和价格监控还能用…

**Comment by evilbutcher** [comment]
感觉应该不是脚本问题，我这里都正常，重新装一下Scriptable试试看

**Comment by yccczzj** [comment]
iCloud 里面两个环境文件下载完了就行了…
