### ISSUE TITLE
请问为什么我在scriptables里面执行了Install Scripts脚本，但其中并没有新增的模块出现呢？

### ISSUE THREAD

**Issue by halleyshx** [evilbutcher/Scriptables#2]
我复制了Env、config、Install Scripts脚本到我手机的scriptables中，然后我在scriptables里面执行了Install Scripts脚本，完成之后，scriptables中并没有新增的模块出现，这个是怎么回事呢？步骤有问题？
![image](https://user-images.githubusercontent.com/24284940/95681079-74971300-0c10-11eb-967d-81039ea1301c.png)
![image](https://user-images.githubusercontent.com/24284940/95681084-79f45d80-0c10-11eb-9ecb-96b64c74cdd1.png)
看log显示是已经下载，但是首页面并没有新增新的脚本

**Comment by evilbutcher** [comment]
env应该不是最新的

**Comment by halleyshx** [comment]
@evilbutcher  是这个问题；我用的是GideonSenku的env，当时看行数差不多，想也许是文件头几行或空行的差别，就没改；刚对比了一下这两个文件，的确是有内容更改；更换env内容之后，好使了，点击下载脚本后，等一会儿 都下载下来了
