### ISSUE TITLE
Config文件配置不生效

### ISSUE THREAD

**Issue by andyyxw** [evilbutcher/Scriptables#5]
尝试更改了Config文件中的 自定义数量和随机颜色，但是一直不生效。试验了一下 整个文件里的配置都不生效：

<img width="314" alt="Xnip2020-10-28_19-20-47" src="https://user-images.githubusercontent.com/41931722/97429778-d9fa3c00-1952-11eb-80f6-4c3ca564c710.png"><img width="316" alt="Xnip2020-10-28_19-17-26" src="https://user-images.githubusercontent.com/41931722/97429772-d8307880-1952-11eb-90d2-fdcac517546d.png"><img width="314" alt="Xnip2020-10-28_19-21-05" src="https://user-images.githubusercontent.com/41931722/97429779-da92d280-1952-11eb-85a5-d7ce61ee3574.png">

**Comment by evilbutcher** [comment]
哦哦，因为采用了ENV生成模板，这个就没用了，不好意思才看到

**Comment by evilbutcher** [comment]
相关文件已恢复~
